name: "SQLCheck Action"
description: "Automatically identify anti-patterns in SQL queries using SQLCheck"
author: "yokawasa"
inputs:
  post-comment:
    description: "Post comment to PR"
    default: true
    required: false
  token:
    description: "Github Token in order to add comment to PR"
    default: ""
    required: true
  risk-level:
    description: "Set of SQL anti-patterns to check: 1,2, or 3"
    default: "3"
    required: false
  verbose:
    description: "Add verbose warnings to SQLCheck analysis result"
    default: false
    required: false
  postfixes:
    description: "List of file postfix to match ( separator: comma )"
    default: "sql"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.post-comment }}
    - ${{ inputs.token }}
    - ${{ inputs.risk-level }}
    - ${{ inputs.verbose }}
    - ${{ inputs.postfixes }}
